/*
MIT License
Copyright (c) 2019 
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
namespace ProfanityFilterNS
{
    /// <summary>
    /// This class contains the profanity list.
    ///
    /// WARNING : This file contains a lot of very offensive terminology. Do not read the content of this source code
    /// file if you are easily offended.
    /// </summary>
    public partial class ProfanityBase
    {
        private readonly string[] _wordList =
        {
             "8===D",
             "8==D",
             "8=D",
             "2 girls 1 cup",
             "two girls one cup",
             "two girls 1 cup",
             "2 girls one cup",
             "2g1c",
             "4r5e",
             "5h1t",
             "5hit",
             "a$$",
             "a$$hole",
             "a_s_s",
             "a2m",
             "a55",
             "a55hole",
             "acrotomophilia",
             "aeolus",
             "ahole",
             "alabama hot pocket",
             "alaskan pipeline",
             "anal",
             "anal impaler",
             "anal leakage",
             "analprobe",
             "anilingus",
             "angrydragon",
             "angry dragon",
             "anus",
             "apeshit",
             "ar5e",
             "arian",
             "arrse",
             "arse",
             "arses",
             "arsehole",
             "aryan",
             "ass fuck",
             "ass hole",
             "assbag",
             "assbandit",
             "assbang",
             "assbanged",
             "assbanger",
             "assbangs",
             "assbite",
             "assclown",
             "asscock",
             "asscracker",
             "asses",
             "assface",
             "assfaces",
             "assfuck",
             "assfucker",
             "ass-fucker",
             "assfukka",
             "assgoblin",
             "assh0le",
             "ass-hat",
             "asshead",
             "assho1e",
             "asshole",
             "assholes",
             "asshopper",
             "ass-jabber",
             "assjacker",
             "asslick",
             "asslicker",
             "assmaster",
             "assmonkey",
             "assmucus",
             "assmunch",
             "assmuncher",
             "assnigger",
             "asspirate",
             "ass-pirate",
             "assshit",
             "assshole",
             "asssucker",
             "asswad",
             "asswhole",
             "asswipe",
             "asswipes",
             "auto erotic",
             "autoerotic",
             "axwound",
             "axewound",
             "axe wound",
             "azazel",
             "azz",
             "b!tch",
             "b00bs",
             "b17ch",
             "b1tch",
             "babeland",
             "baby batter",
             "baby juice",
             "ball gag",
             "ball gravy",
             "ball kicking",
             "ball licking",
             "ball sack",
             "ball sucking",
             "bampot",
             "bang (one's) box",
             "bangbros",
             "bareback",
             "barely legal",
             "barenaked",
             "bastard",
             "bastardo",
             "bastards",
             "bastinado",
             "batty boy",
             "bawdy",
             "bbw",
             "bdsm",
             "beaner",
             "beaners",
             "beardedclam",
             "beastial",
             "beastiality",
             "beatch",
             "beaver cleaver",
             "beaver lips",
             "beef curtain",
             "beef curtains",
             "beeyotch",
             "bellend",
             "beotch",
             "bescumber",
             "bestial",
             "bestiality",
             "bi+ch",
             "biatch",
             "big black",
             "big breasts",
             "big knockers",
             "big tits",
             "bigtits",
             "bimbo",
             "bimbos",
             "bint",
             "birdlock",
             "bitch",
             "bitch tit",
             "bitchass",
             "bitched",
             "bitcher",
             "bitchers",
             "bitches",
             "bitchin",
             "bitching",
             "bitchtits",
             "bitchy",
             "black cock",
             "blonde action",
             "blonde on blonde action",
             "bloodclaat",
             "blow job",
             "blow me",
             "blow mud",
             "blow your load",
             "blowjob",
             "blowjobs",
             "blue waffle",
             "blumpkin",
             "boink",
             "boiolas",
             "bollok",
             "bollox",
             "bondage",
             "boner",
             "boners",
             "boob",
             "boobies",
             "boobs",
             "booby",
             "bookie",
             "boong",
             "booobs",
             "boooobs",
             "booooobs",
             "booooooobs",
             "bootee",
             "bootie",
             "booty call",
             "bosom",
             "bosomy",
             "brotherfucker",
             "brown showers",
             "brunette action",
             "buceta",
             "bugger",
             "bukkake",
             "bulldyke",
             "bullet vibe",
             "bullshits",
             "bullshitted",
             "bullturds",
             "bum boy",
             "bumblefuck",
             "bumclat",
             "buncombe",
             "bunny fucker",
             "bust a load",
             "busty",
             "butt fuck",
             "butt plug",
             "buttcheeks",
             "buttfuck",
             "buttfucka",
             "buttfucker",
             "butthole",
             "buttmuch",
             "buttmunch",
             "butt-pirate",
             "buttplug",
             "c.0.c.k",
             "c.o.c.k.",
             "c.u.n.t",
             "c0ck",
             "c-0-c-k",
             "c0cksucker",
             "caca",
             "cacafuego",
             "cahone",
             "camel toe",
             "cameltoe",
             "camgirl",
             "camslut",
             "camwhore",
             "carpet muncher",
             "carpetmuncher",
             "cawk",
             "cervix",
             "chesticle",
             "chi-chi man",
             "chick with a dick",
             "child-fucker",
             "chinc",
             "chincs",
             "chink",
             "chinky",
             "choad",
             "choade",
             "choc ice",
             "chocolate rosebuds",
             "chode",
             "chodes",
             "chota bags",
             "cipa",
             "circlejerk",
             "cl1t",
             "cleveland steamer",
             "climax",
             "clit",
             "clit licker",
             "clitface",
             "clitfuck",
             "clitoris",
             "clits",
             "clitty",
             "clitty litter",
             "clover clamps",
             "clunge",
             "clusterfuck",
             "cnut",
             "cocain",
             "coccydynia",
             "cock",
             "c-o-c-k",
             "cock pocket",
             "cock snot",
             "cock sucker",
             "cockass",
             "cockbite",
             "cockblock",
             "cockburger",
             "cockeye",
             "cockface",
             "cockfucker",
             "cockhead",
             "cockholster",
             "cockjockey",
             "cockknocker",
             "cockknoker",
             "cocklump",
             "cockmaster",
             "cockmongler",
             "cockmongruel",
             "cockmonkey",
             "cockmunch",
             "cockmuncher",
             "cocknose",
             "cocknugget",
             "cocks",
             "cockshit",
             "cocksmith",
             "cocksmoke",
             "cocksmoker",
             "cocksniffer",
             "cocksuck",
             "cocksucked",
             "cocksucker",
             "cock-sucker",
             "cocksuckers",
             "cocksucking",
             "cocksucks",
             "cocksuka",
             "cocksukka",
             "cockwaffle",
             "coital",
             "cok",
             "cokmuncher",
             "coksucka",
             "coochie",
             "coochy",
             "coon",
             "coonnass",
             "coons",
             "cooter",
             "cop some wood",
             "coprolagnia",
             "coprophilia",
             "corksucker",
             "cornhole",
             "corp whore",
             "corp whore",
             "corpulent",
             "cox",
             "crackwhore",
             "crappy",
             "creampie",
             "cretin",
             "crikey",
             "cripple",
             "crotte",
             "cum",
             "cum chugger",
             "cum dumpster",
             "cum freak",
             "cum guzzler",
             "cumbubble",
             "cumdump",
             "cumdumpster",
             "cumguzzler",
             "cumjockey",
             "cummer",
             "cummin",
             "cumming",
             "cums",
             "cumshot",
             "cumshots",
             "cumslut",
             "cumstain",
             "cumtart",
             "cunilingus",
             "cunillingus",
             "cunnie",
             "cunnilingus",
             "cunny",
             "cunt",
             "c-u-n-t",
             "cunt hair",
             "cuntass",
             "cuntbag",
             "cuntface",
             "cunthole",
             "cunthunter",
             "cuntlick",
             "cuntlicker",
             "cuntrag",
             "cunts",
             "cuntsicle",
             "cuntslut",
             "cunt-struck",
             "cyalis",
             "cyberfuc",
             "cyberfuck",
             "cyberfucked",
             "cyberfucker",
             "cyberfucking",
             "d0ng",
             "d0uch3",
             "d0uche",
             "d1ck",
             "d1ld0",
             "d1ldo",
             "dago",
             "dagos",
             "darkie",
             "darn",
             "date rape",
             "daterape",
             "dawgie-style",
             "deep throat",
             "deepthroat",
             "deggo",
             "dendrophilia",
             "dick",
             "dick head",
             "dick hole",
             "dick shy",
             "dickbag",
             "dickbeaters",
             "dickdipper",
             "dickface",
             "dickflipper",
             "dickfuck",
             "dickfucker",
             "dickhead",
             "dickheads",
             "dickhole",
             "dickish",
             "dick-ish",
             "dickjuice",
             "dickmilk",
             "dickmonger",
             "dickripper",
             "dicks",
             "dicksipper",
             "dickslap",
             "dick-sneeze",
             "dicksucker",
             "dicksucking",
             "dicktickler",
             "dickwad",
             "dickweasel",
             "dickweed",
             "dickwhipper",
             "dickwod",
             "dickzipper",
             "diddle",
             "dike",
             "dildo",
             "dildos",
             "diligaf",
             "dillweed",
             "dimwit",
             "dingle",
             "dingleberries",
             "dingleberry",
             "dink",
             "dinks",
             "dipship",
             "dirsa",
             "div",
             "dlck",
             "dog style",
             "dog-fucker",
             "doggie style",
             "doggiestyle",
             "doggie-style",
             "doggin",
             "dogging",
             "doggy style",
             "doggystyle",
             "doggy-style",
             "dolcett",
             "dommes",
             "dong",
             "donkeyribber",
             "doosh",
             "double dong",
             "double penetration",
             "douch3",
             "douche",
             "douchebag",
             "douchebags",
             "douche-fag",
             "douchewaffle",
             "douchey",
             "dp action",
             "dry hump",
             "duche",
             "dumass",
             "dumb ass",
             "dumbass",
             "dumbasses",
             "dumbcunt",
             "dumbfuck",
             "dumbshit",
             "dummy",
             "dumshit",
             "dvda",
             "dyke",
             "dykes",
             "eat a dick",
             "eat hair pie",
             "eat my ass",
             "ecchi",
             "ejaculate",
             "ejaculated",
             "ejaculates",
             "ejaculating",
             "ejaculating",
             "ejaculatings",
             "ejaculation",
             "ejakulate",
             "erect",
             "erection",
             "erotic",
             "erotism",
             "essohbee",
             "eunuch",
             "extacy",
             "f u c k",
             "f u c k e r",
             "f.u.c.k",
             "f_u_c_k",
             "f4nny",
             "facial",
             "fack",
             "fag",
             "fagbag",
             "fagfucker",
             "fagg",
             "fagged",
             "fagging",
             "faggit",
             "faggitt",
             "faggot",
             "faggotcock",
             "faggots",
             "faggs",
             "fagot",
             "fagots",
             "fags",
             "fagtard",
             "faig",
             "faigt",
             "fanny",
             "fannybandit",
             "fannyflaps",
             "fannyfucker",
             "fanyy",
             "fart",
             "fartknocker",
             "fatass",
             "fcuk",
             "fcuker",
             "fcuking",
             "fecal",
             "feck",
             "fecker",
             "feist",
             "felch",
             "felcher",
             "felching",
             "fellate",
             "fellatio",
             "feltch",
             "feltcher",
             "female squirting",
             "femdom",
             "fenian",
             "fice",
             "figging",
             "fingerbang",
             "fingerfuck",
             "fingerfucked",
             "fingerfucker",
             "fingerfuckers",
             "fingerfucking",
             "fingerfucks",
             "fingering",
             "fist fuck",
             "fisted",
             "fistfuck",
             "fistfucked",
             "fistfucker",
             "fistfuckers",
             "fistfuckings",
             "fistfucks",
             "fisting",
             "fisty",
             "flamer",
             "flange",
             "flaps",
             "fleshflute",
             "flog the log",
             "floozy",
             "foad",
             "foah",
             "fondle",
             "foobar",
             "fook",
             "fooker",
             "foot fetish",
             "footjob",
             "foreskin",
             "freex",
             "frenchify",
             "frigg",
             "frigga",
             "frotting",
             "f-u-c-k",
             "fuck buttons",
             "fuck hole",
             "fuck puppet",
             "fuck trophy",
             "fuck yo mama",
             "fucka",
             "fuckass",
             "fuck-ass",
             "fuckbag",
             "fuck bag",
             "fuck-bitch",
             "fuckboy",
             "fuckbrain",
             "fuckbutt",
             "fuckbutter",
             "fuckersucker",
             "fuckface",
             "fuckhead",
             "fuckheads",
             "fuckhole",
             "fuckin",
             "fucking",
             "fuckings",
             "fuckme",
             "fuck me",
             "fuckmeat",
             "fucknugget",
             "fucknut",
             "fucknutt",
             "fuckoff",
             "fucks",
             "fuckstick",
             "fucktard",
             "fuck-tard",
             "fucktards",
             "fucktart",
             "fucktoy",
             "fucktwat",
             "fuckup",
             "fuckwad",
             "fuckwhit",
             "fuckwit",
             "fuckwitt",
             "fudge packer",
             "fudgepacker",
             "fudge-packer",
             "fuq",
             "futanari",
             "fux",
             "fux0r",
             "fvck",
             "fxck",
             "gae",
             "gai",
             "gang bang",
             "gangbang",
             "gang-bang",
             "gangbanged",
             "gangbangs",
             "gash",
             "gassy ass",
             "gay sex",
             "gayass",
             "gaybob",
             "gaydo",
             "gayfuck",
             "gayfuckist",
             "gaysex",
             "gaytard",
             "gaywad",
             "gender bender",
             "genitals",
             "gey",
             "gfy",
             "ghay",
             "ghey",
             "giant cock",
             "gigolo",
             "gippo",
             "girl on",
             "girl on top",
             "girls gone wild",
             "glans",
             "goatcx",
             "goatse",
             "gokkun",
             "golden shower",
             "goldenshower",
             "golliwog",
             "gonad",
             "gonads",
             "goo girl",
             "gooch",
             "goodpoop",
             "gook",
             "gooks",
             "goregasm",
             "gringo",
             "grope",
             "group sex",
             "gspot",
             "g-spot",
             "guido",
             "guro",
             "h0m0",
             "h0mo",
             "ham flap",
             "handjob",
             "hard on",
             "hardcore",
             "hardcoresex",
             "hebe",
             "heeb",
             "hentai",
             "herp",
             "herpes",
             "herpy",
             "hircismus",
             "hitler",
             "hiv",
             "hoar",
             "hoare",
             "hobag",
             "hoe",
             "hoer",
             "hom0",
             "homey",
             "homo",
             "homodumbshit",
             "homoerotic",
             "homoey",
             "honkey",
             "honky",
             "hooch",
             "hookah",
             "hooker",
             "hoor",
             "hootch",
             "hooter",
             "hooters",
             "hore",
             "horniest",
             "horny",
             "hot carl",
             "hot chick",
             "hotsex",
             "huge fat",
             "hump",
             "humped",
             "humping",
             "hussy",
             "hymen",
             "iap",
             "iberian slap",
             "inbred",
             "incest",
             "injun",
             "jack off",
             "jackhole",
             "jackoff",
             "jack-off",
             "jaggi",
             "jagoff",
             "jail bait",
             "jailbait",
             "jap",
             "japs",
             "jerk off",
             "jerk0ff",
             "jerkass",
             "jerked",
             "jerkoff",
             "jerk-off",
             "jigaboo",
             "jiggaboo",
             "jiggerboo",
             "jism",
             "jiz",
             "jizm",
             "jizm",
             "jizz",
             "jizzed",
             "juggs",
             "jungle bunny",
             "junglebunny",
             "kafir",
             "kawk",
             "kike",
             "kikes",
             "kinbaku",
             "kinkster",
             "klan",
             "knob",
             "knob end",
             "knobbing",
             "knobead",
             "knobed",
             "knobend",
             "knobhead",
             "knobjocky",
             "knobjokey",
             "kock",
             "kondum",
             "kondums",
             "kooch",
             "kooches",
             "kootch",
             "kraut",
             "kum",
             "kummer",
             "kumming",
             "kums",
             "kunilingus",
             "kunja",
             "kunt",
             "kwif",
             "kyke",
             "l3i+ch",
             "l3itch",
             "labia",
             "lech",
             "lemon party",
             "LEN",
             "leper",
             "lesbo",
             "lesbos",
             "lez",
             "lezza/lesbo",
             "lezzie",
             "loin",
             "loins",
             "lolita",
             "lusty",
             "m0f0",
             "m0fo",
             "m45terbate",
             "ma5terb8",
             "ma5terbate",
             "mafugly",
             "mafugly",
             "male squirting",
             "mams",
             "masochist",
             "massa",
             "masterb8",
             "masterbat*",
             "masterbat3",
             "masterbate",
             "master-bate",
             "masterbating",
             "masterbation",
             "masterbations",
             "masturbate",
             "masturbating",
             "masturbation",
             "mcfagget",
             "menage a trois",
             "menses",
             "m-fucking",
             "microphallus",
             "minge",
             "missionary position",
             "mof0",
             "mofo",
             "mo-fo",
             "molest",
             "moo moo foo foo",
             "moolie",
             "muff",
             "muff diver",
             "muff puff",
             "muffdiver",
             "muffdiving",
             "n1gga",
             "n1gger",
             "naked",
             "nambla",
             "nawashi",
             "nazi",
             "nazism",
             "need the dick",
             "negro",
             "neonazi",
             "nig nog",
             "nigaboo",
             "nigg3r",
             "nigg4h",
             "nigga",
             "niggah",
             "niggas",
             "niggaz",
             "nigger",
             "niggers",
             "niggle",
             "niglet",
             "nig-nog",
             "nimphomania",
             "nimrod",
             "ninny",
             "ninnyhammer",
             "nipple",
             "nipples",
             "nob",
             "nob jokey",
             "nobhead",
             "nobjocky",
             "nobjokey",
             "nonce",
             "nympho",
             "nymphomania",
             "octopussy",
             "omorashi",
             "one cup two girls",
             "1 cup 2 girls",
             "one cup 2 girls",
             "1 cup two girls",
             "one guy one jar",
             "1 guy one jar",
             "one guy 1 jar",
             "opiate",
             "organ",
             "orgasim",
             "orgasims",
             "orgasm",
             "orgasmic",
             "orgasms",
             "orgies",
             "ovary",
             "ovum",
             "ovums",
             "p.u.s.s.y.",
             "p.u.s.s.y",
             "p0rn",
             "paedophile",
             "paki",
             "panooch",
             "pecker",
             "peckerhead",
             "pedo",
             "pedobear",
             "pedophile",
             "pedophilia",
             "pedophiliac",
             "peepee",
             "pegging",
             "penial",
             "penile",
             "penis",
             "penisbanger",
             "penisfucker",
             "penispuffer",
             "perversion",
             "phallic",
             "phone sex",
             "phonesex",
             "phuck",
             "phuk",
             "phuked",
             "phuking",
             "phukked",
             "phukking",
             "phuks",
             "phuq",
             "pigfucker",
             "pikey",
             "pillowbiter",
             "pimpis",
             "pinko",
             "piss pig",
             "pisses",
             "pissflaps",
             "piss flaps",
             "pisspig",
             "playboy",
             "polack",
             "pole smoker",
             "polesmoker",
             "pollock",
             "ponyplay",
             "poof",
             "poon",
             "poonani",
             "poonany",
             "poontang",
             "poop chute",
             "poopchute",
             "Poopuncher",
             "porch monkey",
             "porchmonkey",
             "porn",
             "porno",
             "pornography",
             "pornos",
             "potty",
             "prick",
             "pricks",
             "prickteaser",
             "prig",
             "prince albert piercing",
             "prod",
             "pron",
             "prone bone",
             "pronebone",
             "prone-bone",
             "prostitute",
             "prude",
             "psycho",
             "pthc",
             "pube",
             "pubes",
             "pubic",
             "pubis",
             "punani",
             "punanny",
             "punany",
             "punkass",
             "punky",
             "punta",
             "puss",
             "pusse",
             "pussi",
             "pussies",
             "pussy",
             "pussy fart",
             "pussy palace",
             "pussylicking",
             "pussypounder",
             "pussys",
             "pust",
             "puto",
             "queaf",
             "queef",
             "queer",
             "queerbait",
             "queerhole",
             "queero",
             "queers",
             "quicky",
             "quim",
             "racy",
             "raghead",
             "raging boner",
             "rape",
             "raped",
             "raper",
             "rapey",
             "raping",
             "rapist",
             "raunch",
             "rectal",
             "rectum",
             "rectus",
             "reefer",
             "reetard",
             "reich",
             "renob",
             "retard",
             "retarded",
             "reverse cowgirl",
             "revue",
             "rimjaw",
             "rimjob",
             "rimming",
             "ritard",
             "rosy palm",
             "rosy palm and her 5 sisters",
             "rtard",
             "r-tard",
             "rump",
             "rumprammer",
             "ruski",
             "rusty trombone",
             "s&m",
             "sadism",
             "sadist",
             "sambo",
             "sand nigger",
             "sandbar",
             "Sandler",
             "sandnigger",
             "sanger",
             "sausage queen",
             "scag",
             "scantily",
             "scat",
             "schlong",
             "scissoring",
             "scroat",
             "scrog",
             "scrot",
             "scrote",
             "scrud",
             "seduce",
             "seks",
             "semen",
             "sex",
             "sexo",
             "sexual",
             "shag",
             "shagger",
             "shaggin",
             "shagging",
             "shamedame",
             "shaved beaver",
             "shaved pussy",
             "shi+",
             "shibari",
             "shirt lifter",
             "shiz",
             "shiznit",
             "shota",
             "shrimping",
             "sissy",
             "skag",
             "skank",
             "skeet",
             "skullfuck",
             "slag",
             "slanteye",
             "slave",
             "slut",
             "slut bucket",
             "slutbag",
             "slutdumper",
             "slutkiss",
             "sluts",
             "smut",
             "smutty",
             "snatch",
             "snuff",
             "sodom",
             "sodomize",
             "sodomy",
             "souse",
             "soused",
             "spac",
             "sperm",
             "spic",
             "spick",
             "spik",
             "spiks",
             "splooge",
             "splooge moose",
             "spooge",
             "spread legs",
             "spunk",
             "stiffy",
             "strappado",
             "style doggy",
             "suicide girls",
             "sultry women",
             "sumofabiatch",
             "swastikav",
             "swinger",
             "t1t",
             "t1tt1e5",
             "t1tties",
             "taff",
             "taig",
             "tainted love",
             "tawdry",
             "teat",
             "teets",
             "teez",
             "throating",
             "thundercunt",
             "thunder cunt",
             "tight white",
             "tinkle",
             "tit",
             "tit wank",
             "titfuck",
             "titi",
             "tities",
             "tits",
             "titt",
             "tittie5",
             "tittiefucker",
             "titties",
             "titty",
             "tittyfuck",
             "tittyfucker",
             "tittywank",
             "titwank",
             "tongue in a",
             "toots",
             "topless",
             "tosser",
             "towelhead",
             "tramp",
             "tranny",
             "trashy",
             "tribadism",
             "trumped",
             "tub girl",
             "tubgirl",
             "tush",
             "tushy",
             "two fingers",
             "two fingers with tongue",
             "two girls one cup",
             "twunt",
             "twunter",
             "unclefucker",
             "undies",
             "unwed",
             "upskirt",
             "urethra play",
             "urophilia",
             "uterus",
             "v14gra",
             "v1gra",
             "vag",
             "vagina",
             "vajayjay",
             "va-j-j",
             "venus mound",
             "veqtable",
             "violet wand",
             "vixen",
             "vjayjay",
             "vorarephilia",
             "voyeur",
             "vulva",
             "w00se",
             "wang",
             "wanky",
             "wazoo",
             "wedgie",
             "weenie",
             "weewee",
             "wet dream",
             "wetback",
             "wh0re",
             "wh0reface",
             "white power",
             "whiz",
             "whoar",
             "whoralicious",
             "whore",
             "whorealicious",
             "whorebag",
             "whored",
             "whoreface",
             "whorehopper",
             "whorehouse",
             "whores",
             "whoring",
             "wigger",
             "willies",
             "willy",
             "window licker",
             "wog",
             "wop",
             "wrinkled starfish",
             "xrated",
             "x-rated",
             "xx",
             "xxx",
             "yaoi",
             "yeasty",
             "yellow showers",
             "yid",
             "yiffy",
             "zibbi",
             "zoophilia",
             "zubb",
        };
    }
}
