//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curiosity.Police.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Curiosity.Police.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;rouletteTables&quot;: [
        ///    {
        ///      &quot;table&quot;: &quot;vw_prop_casino_roulette_01&quot;,
        ///      &quot;position&quot;: {
        ///        &quot;X&quot;: 1144.814,
        ///        &quot;Y&quot;: 268.2634,
        ///        &quot;Z&quot;: -52.8409
        ///      },
        ///      &quot;heading&quot;: -135,
        ///      &quot;seating&quot;: []
        ///    },
        ///    {
        ///      &quot;table&quot;: &quot;vw_prop_casino_roulette_01&quot;,
        ///      &quot;position&quot;: {
        ///        &quot;X&quot;: 1150.355,
        ///        &quot;Y&quot;: 262.7224,
        ///        &quot;Z&quot;: -52.8409
        ///      },
        ///      &quot;heading&quot;: 45,
        ///      &quot;seating&quot;: []
        ///    },
        ///    {
        ///      &quot;table&quot;: &quot;vw_prop_casino_roulette_01b&quot;,
        ///      &quot;position&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string casinoInterior {
            get {
                return ResourceManager.GetString("casinoInterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;speedCameraDistance&quot;: 12.5,
        ///  &quot;ignoredVehicles&quot;: [
        ///    &quot;police&quot;,
        ///    &quot;police2&quot;
        ///  ],
        ///  &quot;speedLimits&quot;: {
        ///    &quot;Joshua Rd&quot;: 50,
        ///    &quot;East Joshua Road&quot;: 50,
        ///    &quot;Marina Dr&quot;: 35,
        ///    &quot;York St&quot;: 35,
        ///    &quot;Alhambra Dr&quot;: 35,
        ///    &quot;Niland Ave&quot;: 35,
        ///    &quot;Zancudo Ave&quot;: 35,
        ///    &quot;Armadillo Ave&quot;: 35,
        ///    &quot;Algonquin Blvd&quot;: 35,
        ///    &quot;Mountain View Dr&quot;: 35,
        ///    &quot;Cholla Springs Ave&quot;: 35,
        ///    &quot;Panorama Dr&quot;: 40,
        ///    &quot;Lesbos Ln&quot;: 35,
        ///    &quot;Calafia Rd&quot;: 30,
        ///    &quot;North Calafia Way&quot;: 30,
        ///    &quot;Cassidy Trail&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string police {
            get {
                return ResourceManager.GetString("police", resourceCulture);
            }
        }
    }
}
