global using CitizenFX.Core;
global using CitizenFX.Core.Native;
global using Curiosity.Framework.Shared.Attributes;
global using Newtonsoft.Json;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using ScaleformUI;
global using static CitizenFX.Core.Native.API;
