//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curiosity.Core.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Curiosity.Core.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;tips&quot;: [
        ///    {
        ///      &quot;header&quot;: &quot;&lt;span class=\&quot;text-yellow-300 uppercase\&quot;&gt;Welcome to LifeV&lt;/span&gt;&quot;,
        ///      &quot;content&quot;: &quot;&lt;span class=\&quot;text-xl text-red-300\&quot;&gt;&lt;b&gt;We do not tolerate any form of racism​ or hate speech, users found doing so will be banned.&lt;/b&gt;&lt;/span&gt;&lt;ul&gt;&lt;li&gt;&lt;span class=\&quot;text-green-300\&quot;&gt;RESPECT ALL&lt;/span&gt; members of the server, this is a community that will welcome you.&lt;/li&gt;&lt;li&gt;&lt;span class=\&quot;text-red-300\&quot;&gt;DO NOT&lt;/span&gt; Force people to RP. It is not an RP Server it is a PVE simulator ser [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string server_config {
            get {
                return ResourceManager.GetString("server_config", resourceCulture);
            }
        }
    }
}
