namespace Curiosity.Missions.Client.net.Extensions
{
    public enum Subtask
    {
        AimedShootingOnFoot = 4,
        GettingUp = 16,
        MovingOnFootNoCombat = 35,
        MovingOnFootCombat = 38,
        UsingLadder = 47,
        Climbing = 50,
        GettingOffSomething = 51,
        SwappingWeapon = 56,
        RemovingHelmet = 92,
        Dead = 97,
        HittingMelee = 130,
        MeleeCombat = 130,
        SittingInVehicle = 150,
        DrivingWandering = 151,
        ExitingVehicle = 152,
        EnteringVehicleGeneral = 160,
        EnteringVehicleBreakingWindow = 161,
        EnteringVehicleOpeningDoor = 162,
        EnteringVehicleEntering = 163,
        EnteringVehicleClosingDoor = 164,
        ExiingVehicleOpeningDoorExiting = 167,
        ExitingVehicleClosingDoor = 168,
        DrivingGoingToDestinationOrEscorting = 169,
        UsingMountedWeapon = 199,
        InCoverGeneral = 287,
        InCoverFullyInCover = 288,
        AimingThrowable = 289,
        AimingGun = 290,
        Reloading = 298,
        AimingPreventedByObstacle = 299,
        RunningToCover = 300,
        InCoverTransitionToAimingFromCover = 302,
        InCoverTransitionFromAimingFromCover = 303,
        InCoverBlindFire = 304,
        Parachuting = 334,
        PuttingOffParachute = 336,
        JumpingOrClimbingGeneral = 420,
        JumpingAir = 421,
        JumpingFinishingJump = 422
    }
}
