//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curiosity.Core.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Curiosity.Core.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;jobs&quot;: [
        ///    {
        ///      &quot;label&quot;: &quot;Police Officer&quot;,
        ///      &quot;jobEvent&quot;: &quot;job:police:duty&quot;,
        ///      &quot;legacyEvent&quot;: false
        ///    }
        ///  ],
        ///  &quot;suppressedVehicles&quot;: [
        ///    &quot;Lazer&quot;,
        ///    &quot;Titan&quot;,
        ///    &quot;Barracks&quot;,
        ///    &quot;Barracks2&quot;,
        ///    &quot;Barracks3&quot;,
        ///    &quot;Crusader&quot;,
        ///    &quot;Rhino&quot;,
        ///    &quot;Airtug&quot;,
        ///    &quot;Ripley&quot;,
        ///    &quot;Asea2&quot;,
        ///    &quot;Burrito5&quot;,
        ///    &quot;Emperor3&quot;,
        ///    &quot;Mesa2&quot;,
        ///    &quot;PoliceOld1&quot;,
        ///    &quot;PoliceOld2&quot;,
        ///    &quot;RancherXL2&quot;,
        ///    &quot;Sadler2&quot;,
        ///    &quot;Stockade3&quot;,
        ///    &quot;Tractor3&quot;,
        ///    &quot;Buzzard&quot;,
        ///    &quot;Buzzard2&quot;,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;prologue01&quot;,
        ///    &quot;dlcName&quot;: &quot;basegame&quot;,
        ///    &quot;position&quot;: {
        ///      &quot;X&quot;: 4729.80859,
        ///      &quot;Y&quot;: -4553.80469,
        ///      &quot;Z&quot;: 119.623032
        ///    },
        ///    &quot;dimensionMin&quot;: {
        ///      &quot;X&quot;: 3301.531,
        ///      &quot;Y&quot;: -5483.857,
        ///      &quot;Z&quot;: 75.60556
        ///    },
        ///    &quot;dimensionMax&quot;: {
        ///      &quot;X&quot;: 6158.08643,
        ///      &quot;Y&quot;: -3623.75269,
        ///      &quot;Z&quot;: 163.6405
        ///    },
        ///    &quot;entities&quot;: 716,
        ///    &quot;contentFlags&quot;: 1,
        ///    &quot;foundByScripted&quot;: true,
        ///    &quot;interiors&quot;: [],
        ///    &quot;extraData&quot;: {
        ///      &quot;name&quot;: &quot;&quot;,
        ///      &quot;groupNam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string interiors {
            get {
                return ResourceManager.GetString("interiors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;gender&quot;: 0,
        ///    &quot;name&quot;: &quot;MP_Airraces_Tattoo_000_M&quot;,
        ///    &quot;collectionName&quot;: &quot;mpAirraces_overlays&quot;,
        ///    &quot;zoneId&quot;: 0,
        ///    &quot;zoneName&quot;: &quot;ZONE_TORSO&quot;,
        ///    &quot;type&quot;: &quot;TYPE_TATTOO&quot;
        ///  },
        ///  {
        ///    &quot;gender&quot;: 1,
        ///    &quot;name&quot;: &quot;MP_Airraces_Tattoo_000_F&quot;,
        ///    &quot;collectionName&quot;: &quot;mpAirraces_overlays&quot;,
        ///    &quot;zoneId&quot;: 0,
        ///    &quot;zoneName&quot;: &quot;ZONE_TORSO&quot;,
        ///    &quot;type&quot;: &quot;TYPE_TATTOO&quot;
        ///  },
        ///  {
        ///    &quot;gender&quot;: 0,
        ///    &quot;name&quot;: &quot;MP_Airraces_Tattoo_001_M&quot;,
        ///    &quot;collectionName&quot;: &quot;mpAirraces_overlays&quot;,
        ///    &quot;zoneId&quot;: 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string overlays {
            get {
                return ResourceManager.GetString("overlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;scenario&quot;: &quot;Agency_Heist_Peds&quot;,
        ///    &quot;enabled&quot;: false
        ///  },
        ///  {
        ///    &quot;scenario&quot;: &quot;ALAMO_PLANES&quot;,
        ///    &quot;enabled&quot;: false
        ///  },
        ///  {
        ///    &quot;scenario&quot;: &quot;AMMUNATION&quot;,
        ///    &quot;enabled&quot;: true
        ///  },
        ///  {
        ///    &quot;scenario&quot;: &quot;ARMENIAN_CATS&quot;,
        ///    &quot;enabled&quot;: true
        ///  },
        ///  {
        ///    &quot;scenario&quot;: &quot;ARMY_GUARD&quot;,
        ///    &quot;enabled&quot;: true
        ///  },
        ///  {
        ///    &quot;scenario&quot;: &quot;ATTRACT_PAP&quot;,
        ///    &quot;enabled&quot;: true
        ///  },
        ///  {
        ///    &quot;scenario&quot;: &quot;BLIMP&quot;,
        ///    &quot;enabled&quot;: true
        ///  },
        ///  {
        ///    &quot;scenario&quot;: &quot;CanyonCliffs&quot;,
        ///    &quot;enabled&quot;: false [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string scenarios {
            get {
                return ResourceManager.GetString("scenarios", resourceCulture);
            }
        }
    }
}
