//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curiosity.Core.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Curiosity.Core.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;jobs&quot;: [
        ///    {
        ///      &quot;label&quot;: &quot;Unemployed&quot;,
        ///      &quot;jobEvent&quot;: &quot;job:unemployed&quot;,
        ///      &quot;legacyEvent&quot;: false
        ///    },
        ///    {
        ///      &quot;label&quot;: &quot;Police Officer [PvP]&quot;,
        ///      &quot;jobEvent&quot;: &quot;job:police:duty&quot;,
        ///      &quot;legacyEvent&quot;: false
        ///    }
        ///  ],
        ///  &quot;outfits&quot;: [
        ///    {
        ///      &quot;label&quot;: &quot;LSPD&quot;,
        ///      &quot;male&quot;: false,
        ///      &quot;components&quot;: [
        ///        {
        ///          &quot;component&quot;: 1,
        ///          &quot;drawable&quot;: 0,
        ///          &quot;texture&quot;: 0
        ///        },
        ///        {
        ///          &quot;component&quot;: 3,
        ///          &quot;drawable&quot;: 3,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;gender&quot;: 0,
        ///    &quot;name&quot;: &quot;MP_Airraces_Tattoo_000_M&quot;,
        ///    &quot;collectionName&quot;: &quot;mpAirraces_overlays&quot;,
        ///    &quot;zoneId&quot;: 0,
        ///    &quot;zoneName&quot;: &quot;ZONE_TORSO&quot;,
        ///    &quot;type&quot;: &quot;TYPE_TATTOO&quot;
        ///  },
        ///  {
        ///    &quot;gender&quot;: 1,
        ///    &quot;name&quot;: &quot;MP_Airraces_Tattoo_000_F&quot;,
        ///    &quot;collectionName&quot;: &quot;mpAirraces_overlays&quot;,
        ///    &quot;zoneId&quot;: 0,
        ///    &quot;zoneName&quot;: &quot;ZONE_TORSO&quot;,
        ///    &quot;type&quot;: &quot;TYPE_TATTOO&quot;
        ///  },
        ///  {
        ///    &quot;gender&quot;: 0,
        ///    &quot;name&quot;: &quot;MP_Airraces_Tattoo_001_M&quot;,
        ///    &quot;collectionName&quot;: &quot;mpAirraces_overlays&quot;,
        ///    &quot;zoneId&quot;: 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string overlays {
            get {
                return ResourceManager.GetString("overlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;speedCameraDistance&quot;: 100,
        ///  &quot;speedCameraWidth&quot;: 15,
        ///  &quot;speedLimits&quot;: {
        ///    &quot;2896128334&quot;: 80,
        ///    &quot;2552845347&quot;: 80,
        ///    &quot;776581733&quot;: 80,
        ///    &quot;2600585507&quot;: 80,
        ///    &quot;3362327680&quot;: 80,
        ///    &quot;302348953&quot;: 80,
        ///    &quot;4124992785&quot;: 80,
        ///    &quot;3436239235&quot;: 50,
        ///    &quot;3168230186&quot;: 50,
        ///    &quot;127506487&quot;: 50,
        ///    &quot;3474613771&quot;: 50,
        ///    &quot;3885181515&quot;: 80,
        ///    &quot;1759459593&quot;: 50,
        ///    &quot;2226519225&quot;: 50,
        ///    &quot;127435642&quot;: 50,
        ///    &quot;4155137&quot;: 50,
        ///    &quot;4174973413&quot;: 50,
        ///    &quot;2502989037&quot;: 50,
        ///    &quot;2464268432&quot;: 50
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string police {
            get {
                return ResourceManager.GetString("police", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;scenario&quot;: &quot;Agency_Heist_Peds&quot;,
        ///    &quot;enabled&quot;: false
        ///  },
        ///  {
        ///    &quot;scenario&quot;: &quot;ALAMO_PLANES&quot;,
        ///    &quot;enabled&quot;: false
        ///  },
        ///  {
        ///    &quot;scenario&quot;: &quot;AMMUNATION&quot;,
        ///    &quot;enabled&quot;: true
        ///  },
        ///  {
        ///    &quot;scenario&quot;: &quot;ARMENIAN_CATS&quot;,
        ///    &quot;enabled&quot;: true
        ///  },
        ///  {
        ///    &quot;scenario&quot;: &quot;ARMY_GUARD&quot;,
        ///    &quot;enabled&quot;: true
        ///  },
        ///  {
        ///    &quot;scenario&quot;: &quot;ATTRACT_PAP&quot;,
        ///    &quot;enabled&quot;: true
        ///  },
        ///  {
        ///    &quot;scenario&quot;: &quot;BLIMP&quot;,
        ///    &quot;enabled&quot;: false
        ///  },
        ///  {
        ///    &quot;scenario&quot;: &quot;CanyonCliffs&quot;,
        ///    &quot;enabled&quot;: fals [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string scenarios {
            get {
                return ResourceManager.GetString("scenarios", resourceCulture);
            }
        }
    }
}
