//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curiosity.Core.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Curiosity.Core.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;jobs&quot;: [
        ///    {
        ///      &quot;label&quot;: &quot;Unemployed&quot;,
        ///      &quot;jobEvent&quot;: &quot;job:unemployed&quot;,
        ///      &quot;legacyEvent&quot;: false
        ///    },
        ///    {
        ///      &quot;label&quot;: &quot;Police Officer&quot;,
        ///      &quot;jobEvent&quot;: &quot;job:police:duty&quot;,
        ///      &quot;legacyEvent&quot;: false
        ///    }
        ///  ],
        ///  &quot;eletricVehicles&quot;: [
        ///    &quot;imorgon&quot;,
        ///    &quot;p90d&quot;,
        ///    &quot;teslasemi&quot;,
        ///    &quot;tezeract&quot;,
        ///    &quot;neon&quot;,
        ///    &quot;raiden&quot;,
        ///    &quot;cyclone&quot;,
        ///    &quot;caddy3&quot;,
        ///    &quot;voltic2&quot;,
        ///    &quot;khamelion&quot;,
        ///    &quot;dilettante2&quot;,
        ///    &quot;caddy2&quot;,
        ///    &quot;forklift&quot;,
        ///    &quot;caddy&quot;,
        ///    &quot;airtug&quot;,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;prologue01&quot;,
        ///    &quot;dlcName&quot;: &quot;basegame&quot;,
        ///    &quot;position&quot;: {
        ///      &quot;X&quot;: 4729.80859,
        ///      &quot;Y&quot;: -4553.80469,
        ///      &quot;Z&quot;: 119.623032
        ///    },
        ///    &quot;dimensionMin&quot;: {
        ///      &quot;X&quot;: 3301.531,
        ///      &quot;Y&quot;: -5483.857,
        ///      &quot;Z&quot;: 75.60556
        ///    },
        ///    &quot;dimensionMax&quot;: {
        ///      &quot;X&quot;: 6158.08643,
        ///      &quot;Y&quot;: -3623.75269,
        ///      &quot;Z&quot;: 163.6405
        ///    },
        ///    &quot;entities&quot;: 716,
        ///    &quot;contentFlags&quot;: 1,
        ///    &quot;foundByScripted&quot;: true,
        ///    &quot;interiors&quot;: [],
        ///    &quot;extraData&quot;: {
        ///      &quot;name&quot;: &quot;&quot;,
        ///      &quot;groupNam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string interiors {
            get {
                return ResourceManager.GetString("interiors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;gender&quot;: 0,
        ///    &quot;name&quot;: &quot;MP_Airraces_Tattoo_000_M&quot;,
        ///    &quot;collectionName&quot;: &quot;mpAirraces_overlays&quot;,
        ///    &quot;zoneId&quot;: 0,
        ///    &quot;zoneName&quot;: &quot;ZONE_TORSO&quot;,
        ///    &quot;type&quot;: &quot;TYPE_TATTOO&quot;
        ///  },
        ///  {
        ///    &quot;gender&quot;: 1,
        ///    &quot;name&quot;: &quot;MP_Airraces_Tattoo_000_F&quot;,
        ///    &quot;collectionName&quot;: &quot;mpAirraces_overlays&quot;,
        ///    &quot;zoneId&quot;: 0,
        ///    &quot;zoneName&quot;: &quot;ZONE_TORSO&quot;,
        ///    &quot;type&quot;: &quot;TYPE_TATTOO&quot;
        ///  },
        ///  {
        ///    &quot;gender&quot;: 0,
        ///    &quot;name&quot;: &quot;MP_Airraces_Tattoo_001_M&quot;,
        ///    &quot;collectionName&quot;: &quot;mpAirraces_overlays&quot;,
        ///    &quot;zoneId&quot;: 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string overlays {
            get {
                return ResourceManager.GetString("overlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;speedCameraDistance&quot;: 12.5,
        ///  &quot;ignoredVehicles&quot;: [
        ///    &quot;police&quot;,
        ///    &quot;police2&quot;
        ///  ],
        ///  &quot;speedLimits&quot;: {
        ///    &quot;Joshua Rd&quot;: 50,
        ///    &quot;East Joshua Road&quot;: 50,
        ///    &quot;Marina Dr&quot;: 35,
        ///    &quot;York St&quot;: 35,
        ///    &quot;Alhambra Dr&quot;: 35,
        ///    &quot;Niland Ave&quot;: 35,
        ///    &quot;Zancudo Ave&quot;: 35,
        ///    &quot;Armadillo Ave&quot;: 35,
        ///    &quot;Algonquin Blvd&quot;: 35,
        ///    &quot;Mountain View Dr&quot;: 35,
        ///    &quot;Cholla Springs Ave&quot;: 35,
        ///    &quot;Panorama Dr&quot;: 40,
        ///    &quot;Lesbos Ln&quot;: 35,
        ///    &quot;Calafia Rd&quot;: 30,
        ///    &quot;North Calafia Way&quot;: 30,
        ///    &quot;Cassidy Trail&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string police {
            get {
                return ResourceManager.GetString("police", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;scenario&quot;: &quot;Agency_Heist_Peds&quot;,
        ///    &quot;enabled&quot;: false
        ///  },
        ///  {
        ///    &quot;scenario&quot;: &quot;ALAMO_PLANES&quot;,
        ///    &quot;enabled&quot;: false
        ///  },
        ///  {
        ///    &quot;scenario&quot;: &quot;AMMUNATION&quot;,
        ///    &quot;enabled&quot;: true
        ///  },
        ///  {
        ///    &quot;scenario&quot;: &quot;ARMENIAN_CATS&quot;,
        ///    &quot;enabled&quot;: true
        ///  },
        ///  {
        ///    &quot;scenario&quot;: &quot;ARMY_GUARD&quot;,
        ///    &quot;enabled&quot;: true
        ///  },
        ///  {
        ///    &quot;scenario&quot;: &quot;ATTRACT_PAP&quot;,
        ///    &quot;enabled&quot;: true
        ///  },
        ///  {
        ///    &quot;scenario&quot;: &quot;BLIMP&quot;,
        ///    &quot;enabled&quot;: true
        ///  },
        ///  {
        ///    &quot;scenario&quot;: &quot;CanyonCliffs&quot;,
        ///    &quot;enabled&quot;: false [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string scenarios {
            get {
                return ResourceManager.GetString("scenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Objects&quot;: {
        ///    &quot;MapObject&quot;: [
        ///      {
        ///        &quot;Type&quot;: &quot;Prop&quot;,
        ///        &quot;Position&quot;: {
        ///          &quot;X&quot;: -898.862549,
        ///          &quot;Y&quot;: -708.4136,
        ///          &quot;Z&quot;: 31.2379112
        ///        },
        ///        &quot;Rotation&quot;: {
        ///          &quot;X&quot;: 0,
        ///          &quot;Y&quot;: -0,
        ///          &quot;Z&quot;: 92.99932
        ///        },
        ///        &quot;Hash&quot;: &quot;1919058329&quot;,
        ///        &quot;Dynamic&quot;: false,
        ///        &quot;Quaternion&quot;: {
        ///          &quot;X&quot;: 0,
        ///          &quot;Y&quot;: 0,
        ///          &quot;Z&quot;: 0.725370347,
        ///          &quot;W&quot;: 0.6883587
        ///        },
        ///        &quot;Door&quot;: false
        ///      },
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string speedCameras {
            get {
                return ResourceManager.GetString("speedCameras", resourceCulture);
            }
        }
    }
}
