namespace Curiosity.Systems.Library.Enums
{
    public enum eClothingType
    {
        None = -1,
        CapBackward,
        CapForward,
        CasualJacket,
        CasualTShirt,
        Chain,
        Earrings,
        FullSuit,
        Glasses,
        Hat,
        Hoodie,
        Jacket,
        Outfit,
        Pants,
        Polo,
        Shirt,
        Shoes,
        Shorts,
        SportShades,
        StreetShades,
        SuitJacket,
        SuitJacketButtoned,
        SuitPants,
        SuitTie,
        SuitVest,
        TankTop,
        Top,
        TShirt,
        Vest,
    }
}
